(source gnu)
(source melpa)

(package-file "morgana.el")

(development
 (depends-on "f")
 (depends-on "s")
 (depends-on "dash")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
